/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * AI Document Vault API
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
  status: string;
}

export interface ErrorResponse {
  error: string;
}

export interface Document {
  id: number;
  name: string;
  objectPath: string;
  mimeType: string;
  /** @nullable */
  sizeBytes?: number | null;
  /** @nullable */
  extractedText?: string | null;
  /**
     * 0G Storage Merkle root hash
     * @nullable
     */
  rootHash?: string | null;
  /**
     * 0G Storage transaction hash
     * @nullable
     */
  txHash?: string | null;
  /** Storage backend used (replit or zerog) */
  storageProvider: string;
  createdAt: string;
  updatedAt: string;
}

export interface DocumentInput {
  name: string;
  objectPath: string;
  mimeType: string;
  /** @nullable */
  sizeBytes?: number | null;
}

export interface VaultStats {
  totalDocuments: number;
  totalSizeBytes: number;
  totalConversations: number;
  documentsWithText: number;
}

export interface Conversation {
  id: number;
  title: string;
  /** @nullable */
  documentId?: number | null;
  /** @nullable */
  documentName?: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface ConversationInput {
  title: string;
  /** @nullable */
  documentId?: number | null;
}

export type MessageRole = typeof MessageRole[keyof typeof MessageRole];


export const MessageRole = {
  user: 'user',
  assistant: 'assistant',
} as const;

export interface Message {
  id: number;
  conversationId: number;
  role: MessageRole;
  content: string;
  createdAt: string;
}

export interface ConversationWithMessages {
  id: number;
  title: string;
  /** @nullable */
  documentId?: number | null;
  /** @nullable */
  documentName?: string | null;
  messages: Message[];
  createdAt: string;
  updatedAt: string;
}

export interface MessageInput {
  content: string;
}

export interface UploadUrlRequest {
  name: string;
  size: number;
  contentType: string;
}

export interface UploadUrlResponse {
  uploadURL: string;
  objectPath: string;
}

export type ListDocumentsParams = {
/**
 * Full-text search query
 */
search?: string;
/**
 * Max results to return
 */
limit?: number;
/**
 * Pagination offset
 */
offset?: number;
};

