/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * AI Document Vault API
 * OpenAPI spec version: 0.1.0
 */
import type { Message } from './message';

export interface ConversationWithMessages {
  id: number;
  title: string;
  /** @nullable */
  documentId?: number | null;
  /** @nullable */
  documentName?: string | null;
  messages: Message[];
  createdAt: Date;
  updatedAt: Date;
}
