/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * AI Document Vault API
 * OpenAPI spec version: 0.1.0
 */
export interface Conversation {
    id: number;
    title: string;
    /** @nullable */
    documentId?: number | null;
    /** @nullable */
    documentName?: string | null;
    createdAt: Date;
    updatedAt: Date;
}
//# sourceMappingURL=conversation.d.ts.map