/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * AI Document Vault API
 * OpenAPI spec version: 0.1.0
 */
export interface ConversationInput {
    title: string;
    /** @nullable */
    documentId?: number | null;
}
//# sourceMappingURL=conversationInput.d.ts.map