/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * AI Document Vault API
 * OpenAPI spec version: 0.1.0
 */
export interface Document {
    id: number;
    name: string;
    objectPath: string;
    mimeType: string;
    /** @nullable */
    sizeBytes?: number | null;
    /** @nullable */
    extractedText?: string | null;
    /**
       * 0G Storage Merkle root hash
       * @nullable
       */
    rootHash?: string | null;
    /**
       * 0G Storage transaction hash
       * @nullable
       */
    txHash?: string | null;
    /** Storage backend used (replit or zerog) */
    storageProvider: string;
    createdAt: Date;
    updatedAt: Date;
}
//# sourceMappingURL=document.d.ts.map