/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * AI Document Vault API
 * OpenAPI spec version: 0.1.0
 */
export type ListDocumentsParams = {
    /**
     * Full-text search query
     */
    search?: string;
    /**
     * Max results to return
     */
    limit?: number;
    /**
     * Pagination offset
     */
    offset?: number;
};
//# sourceMappingURL=listDocumentsParams.d.ts.map