/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * AI Document Vault API
 * OpenAPI spec version: 0.1.0
 */
export interface UploadUrlResponse {
    uploadURL: string;
    objectPath: string;
}
//# sourceMappingURL=uploadUrlResponse.d.ts.map